### ISSUE TITLE
The weapon attack button is no longer working

### ISSUE THREAD

**Issue by Unikatze** [Rostaen/goblin-slayer-ttrpg#10]
When you click it nothing happens. 

The damage button is working fine though.

**Comment by Rostaen** [comment]
There may be a small version transition problem between the UI Warnings that I've set up and having a token targeted first. The code that I'm working with now (likely will be v0.10.6) has proper code setup to warn people when they don't have a token targeted for attacks. There is also a small bug that I found with the Slice skill and any weapon (that is being fixed in v0.10.6 as well).

Try this and let me know if your attacks are working now.

1. Right-click the target token for the attack and click the target to "activate target" _or_ hover over the target token and click 'T' on your keyboard.
2. Run the attack like normal.
